language: python
python:
  - "2.6"
  - "2.7"
install:
  # Self-install for setup.py-driven deps
  - pip install -e .
script: python test.py --verbose
notifications:
  irc:
    channels: "irc.freenode.org#paramiko"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false
